name: Michael Davis
title: Web Dev Kit
description: This complete toolkit merges jekyll, gulp, and angular to help easily create dynamic websites on the fly
email: michael.e.davisjr@gmail.com
locale: en-Us
markdown: redcarpet
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md"]
